import { X, Eye, Aperture, Calendar, UserSquare, Bookmark } from 'lucide-react';

interface SpotlightModalProps {
  isOpen: boolean;
  onClose: () => void;
  title: string;
}

export function SpotlightModal({ isOpen, onClose, title }: SpotlightModalProps) {
  if (!isOpen) return null;

  const getButtons = () => {
    if (title.includes('Teleport')) {
      return (
        <>
          <button
            onClick={() => handleAction('Try This Look', 'Kyoto Cherry Blossom')}
            className="w-full p-3 text-lg text-white rounded-xl bg-purple-500 shadow-xl shadow-purple-400/40 hover:bg-purple-600 transition-transform active:scale-95"
          >
            <Eye className="w-5 h-5 inline mr-2" /> Try This Look
          </button>
          <button
            onClick={() => handleAction('Teleport Now', 'Kyoto Cherry Blossom')}
            className="w-full p-3 text-lg text-white rounded-xl bg-pink-500 shadow-xl shadow-pink-400/40 hover:bg-pink-600 transition-transform active:scale-95"
          >
            <Aperture className="w-5 h-5 inline mr-2" /> Teleport Now
          </button>
        </>
      );
    } else if (title.includes('Artist')) {
      return (
        <>
          <button
            onClick={() => handleAction('Book Now', 'Janani S.')}
            className="w-full p-3 text-lg text-white rounded-xl bg-purple-500 shadow-xl shadow-purple-400/40 hover:bg-purple-600 transition-transform active:scale-95"
          >
            <Calendar className="w-5 h-5 inline mr-2" /> Book Now
          </button>
          <button
            onClick={() => handleAction('View Profile', 'Janani S.')}
            className="w-full p-3 text-lg text-white rounded-xl bg-pink-500 shadow-xl shadow-pink-400/40 hover:bg-pink-600 transition-transform active:scale-95"
          >
            <UserSquare className="w-5 h-5 inline mr-2" /> View Profile
          </button>
        </>
      );
    } else {
      return (
        <>
          <button
            onClick={() => handleAction('Try This Look', 'Neon Euphoria Liner')}
            className="w-full p-3 text-lg text-white rounded-xl bg-purple-500 shadow-xl shadow-purple-400/40 hover:bg-purple-600 transition-transform active:scale-95"
          >
            <Eye className="w-5 h-5 inline mr-2" /> Try This Look
          </button>
          <button
            onClick={() => handleAction('Save Look', 'Neon Euphoria Liner')}
            className="w-full p-3 text-lg text-white rounded-xl bg-pink-500 shadow-xl shadow-pink-400/40 hover:bg-pink-600 transition-transform active:scale-95"
          >
            <Bookmark className="w-5 h-5 inline mr-2" /> Save Look
          </button>
        </>
      );
    }
  };

  const handleAction = (action: string, item: string) => {
    console.log(`Spotlight Action: ${action} on ${item}`);
    onClose();
  };

  return (
    <div
      className={`fixed inset-0 bg-white/95 backdrop-blur-lg z-50 flex items-center justify-center transition-opacity duration-300 ${
        isOpen ? 'opacity-100 pointer-events-auto' : 'opacity-0 pointer-events-none'
      }`}
    >
      <div
        className={`modal-bg p-6 rounded-3xl max-w-sm w-11/12 transform transition-transform duration-300 relative border border-gray-200 ${
          isOpen ? 'scale-100' : 'scale-95'
        }`}
      >
        <button
          onClick={onClose}
          className="absolute top-4 right-4 text-gray-500 hover:text-gray-800 transition-colors"
          aria-label="Close"
        >
          <X className="w-6 h-6" />
        </button>

        <h4 className="text-xs text-gray-500 mb-2">Glow Spotlight Preview</h4>
        <h3 className="text-2xl text-transparent bg-clip-text glow-accent mb-4">{title}</h3>

        <img
          src="https://placehold.co/400x200/FFD6E8/1f2937?text=Quick+Video+Preview"
          alt="Preview"
          className="w-full rounded-xl mb-4 object-cover border border-pink-300"
          onError={(e) => {
            e.currentTarget.src = 'https://placehold.co/400x200/FFD6E8/1f2937?text=Quick+Video+Preview';
          }}
        />

        <p className="text-sm text-gray-600 mb-6">
          Explore this highly recommended feature, generated by our proprietary AI/AR system. Tap
          an action to proceed.
        </p>

        <div className="space-y-3">{getButtons()}</div>
      </div>
    </div>
  );
}
